<a href="https://colab.research.google.com/github/kyook17/UIUC_BADM/blob/main/BADM576_DS/HW_8_Kiwook_Song.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **0. Install Library**

In [156]:
!pip install --upgrade scikit-learn

In [157]:
!pip install autoviz

# **1. Data Loading**




In [158]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from autoviz.AutoViz_Class import AutoViz_Class

df = pd.read_csv('https://raw.githubusercontent.com/ashish-cell/BADM-211-FA21/main/Data/laptop_hw6.csv')
df.head()

Transaction_ID  Configuration  Screen_Size  Battery_Life  RAM  \
0        5622            51           15             4        2    
1       52758           695           17             5        4    
2         977           299           15             6        1    
3      215756           303           15             6        1    
4      294662           394           15             6        4    

   Processor_Speeds Integrated_Wireless  HD_Size Bundled_Applications  \
0         1.5                Yes            80            Yes           
1         2.0                Yes           300            Yes           
2         1.5                 No            80            Yes           
3         1.5                 No           300            Yes           
4         1.5                 No            40             No           

   Retail_Price  
0      460.0     
1        NaN     
2      490.0     
3      525.0     
4      550.0

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5963 entries, 0 to 5962
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Transaction_ID        5963 non-null   int64  
 1   Configuration         5963 non-null   int64  
 2   Screen_Size           5963 non-null   int64  
 3   Battery_Life          5963 non-null   int64  
 4   RAM                   5963 non-null   int64  
 5   Processor_Speeds      5963 non-null   float64
 6   Integrated_Wireless   5963 non-null   object 
 7   HD_Size               5963 non-null   int64  
 8   Bundled_Applications  5963 non-null   object 
 9   Retail_Price          5670 non-null   float64
dtypes: float64(2), int64(6), object(2)
memory usage: 466.0+ KB


In [160]:
df.isnull().sum()

Transaction_ID            0
Configuration             0
Screen_Size               0
Battery_Life              0
RAM                       0
Processor_Speeds          0
Integrated_Wireless       0
HD_Size                   0
Bundled_Applications      0
Retail_Price            293
dtype: int64

In [161]:
df.duplicated().sum() # There are a few duplicate rows that need to be removed.

12

In [162]:
df.drop_duplicates(inplace = True) # Drop duplicated value
df=df.dropna(subset=['Retail_Price']) # Delete NaN row

In [163]:
# Classifying variables using AutoViz

AV = AutoViz_Class()
AV.AutoViz("", depVar= "Retail_Price",dfte = df)

Shape of your Data Set loaded: (5658, 10)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  1
    Number of Integer-Categorical Columns =  4
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  2
    Number of Numeric-Boolean Columns =  1
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    9 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Transaction_ID']

################ Regression problem #############

Could not draw some Distribution Plots
All Plots done
Time to run AutoViz = 2 seconds 

 ###################### AUTO VISUALIZATION Completed ########################


Configuration  Screen_Size  Battery_Life  RAM  Processor_Speeds  \
0           51           15             4        2          1.5         
2          299           15             6        1          1.5         
3          303           15             6        1          1.5         
4          394           15             6        4          1.5         
5          603           17             5        1          2.0         
...             ...          ...           ...  ...               ...   
5958       111           15             4        4          1.5         
5959       752           17             6        1          2.0         
5960       329           15             6        1          2.4         
5961       370           15             6        2          2.4         
5962        35           15             4        1          2.4         

     Integrated_Wireless  HD_Size Bundled_Applications  Retail_Price  
0             Yes            80            Yes              460.0     
2              No            80            Yes              490.0     
3              No           300            Yes              525.0     
4              No            40             No              550.0     
5              No            80            Yes              364.0     
...                  ...      ...                  ...           ...  
5958           No           300            Yes              620.0     
5959           No           300             No              620.0     
5960           No            40            Yes              485.0     
5961          Yes            40             No              490.0     
5962          Yes            80            Yes              435.0     

[5658 rows x 9 columns]

In [164]:
df.describe()

Transaction_ID  Configuration  Screen_Size  Battery_Life      RAM      \
count     5658.000000   5658.000000   5658.000000   5658.000000  5658.000000   
mean    148656.635737    374.187522     15.789325      4.963945     2.115412   
std      85411.943998    229.722018      0.977643      0.815555     1.159510   
min         71.000000      1.000000     15.000000      4.000000     1.000000   
25%      75919.750000    183.000000     15.000000      4.000000     1.000000   
50%     146348.500000    342.000000     15.000000      5.000000     2.000000   
75%     222257.250000    556.000000     17.000000      6.000000     2.000000   
max     297561.000000    864.000000     17.000000      6.000000     4.000000   

       Processor_Speeds    HD_Size    Retail_Price  
count     5658.000000    5658.000000   5658.000000  
mean         1.930134     132.325910    508.057618  
std          0.364723      97.560116    104.920473  
min          1.500000      40.000000    182.000000  
25%          1.500000      40.000000    440.000000  
50%          2.000000      80.000000    500.000000  
75%          2.400000     120.000000    575.000000  
max          2.400000     300.000000    890.000000

In [165]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [166]:
!pip install -U feature-engine # This a another library that provides very useful functions for data preprocessing.

In [167]:
from feature_engine.encoding import RareLabelEncoder # For encoding rare labels; we could have also used sklearn encoder with infrequent categories
from feature_engine.outliers import Winsorizer # We can use outlier handler; there is outlier_clipper also.

# **2. Making Pipeline**

### 2.1 Pipelines for Numeric Variables

In [168]:
# Pipeline for Skewed numeric variables
skewed_num_pipe  = Pipeline(steps = [("imp", SimpleImputer(strategy= "median")),
                                     ("out", Winsorizer(capping_method='quantiles', tail='both', fold=.06))]) # several capping methods: gaussian; iqr; quantile. Fold paramater indicates how far from the central position.

# Pipeline for normally distributed numeric variables
norm_num_pipe = Pipeline(steps = [("imp", SimpleImputer(strategy= "mean", add_indicator= True))])


# Pipeline for variables that need discretization - We decide which ones to discretize based on logic
disc_pipe = Pipeline(steps = [("imp", SimpleImputer(strategy= "median", add_indicator= True)),
                              ("disc", KBinsDiscretizer(strategy= "equal_width", encode = "ordinal"))])

### 2.2 Pipelines for Non-numeric Variables

In [169]:
# Nominal categorical variables
nom_cat_pipe = Pipeline(steps = [("imp", SimpleImputer(strategy= "constant", fill_value = "missing")),
                                 ("ohe", OneHotEncoder(sparse_output=False))])

# Ordinal Catgeorical variables
ord_cat_pipe = Pipeline(steps = [("imp", SimpleImputer(strategy= "most_frequent", add_indicator = True)),
                                 ("ord", OrdinalEncoder( ))])

# Pipeline for Categorical variables with rare categories
rare_cat_pipe = Pipeline(steps = [("imp", SimpleImputer(strategy= "constant", fill_value = "rare")), ("rare", RareLabelEncoder(tol=0.05, n_categories=4)), ("ohe", OneHotEncoder(sparse_output=False))])

### 2.3 Create lists of variables of each type.

In [170]:
num_var = ['Configuration', 'Screen_Size', 'Battery_Life', 'RAM', 'Processor_Speeds', 'HD_Size']
cat_var = ['Integrated_Wireless', 'Bundled_Applications']

In [171]:
# Identify the numeric variables category

from scipy.stats import shapiro, skew, kurtosis

# Function to perform Shapiro-Wilk test and calculate skewness and kurtosis
def analyze_normality(df, variables):
    results = {}
    for var in variables:
        # Shapiro-Wilk test
        stat, p_value = shapiro(df[var].dropna())  # Dropping NA values for the test
        # Skewness and Kurtosis
        skewness = skew(df[var].dropna())
        kurt = kurtosis(df[var].dropna(), fisher=True)  # Fisher=True returns excess kurtosis

        results[var] = {'Shapiro-Wilk Stat': stat, 'p-value': p_value, 'Skewness': skewness, 'Kurtosis': kurt}

    return pd.DataFrame(results).T

# Analyzing the normality of the same subset of variables
normality_results = analyze_normality(df, num_var)
normality_results

Shapiro-Wilk Stat     p-value    Skewness  Kurtosis
Configuration         0.960314       9.318616e-37  0.300651 -0.959627
Screen_Size           0.620263       0.000000e+00  0.431024 -1.814218
Battery_Life          0.792869       0.000000e+00  0.066241 -1.493349
RAM                   0.756998       0.000000e+00  0.719544 -0.964433
Processor_Speeds      0.792055       0.000000e+00  0.009404 -1.498452
HD_Size               0.744687       0.000000e+00  0.947486 -0.714978

In [172]:
# Nominal categorical variables from the dataset
nom_cat_vars = ["Integrated_Wireless", "Bundled_Applications"]

# Ordinal categorical variables from the dataset
ord_cat_vars = []

# Categorical variables with rare categories
rare_cat_vars = []

# Numeric variables that require discretization
disc_num_vars = []

# Numeric variables that are normally distributed
norm_num_vars = ["Battery_Life", "Processor_Speeds"]

# Numeric variables that ahave skew in them
skewed_num_vars = ["Configuration", "Screen_Size", "RAM", "HD_Size"]

# Variables that have some dates in them. We will use our own created date transformer
date_vars = []

In [173]:
preprocessor = ColumnTransformer(transformers = [("nom", nom_cat_pipe, nom_cat_vars),
                                                 ("ord", ord_cat_pipe, ord_cat_vars),
                                                 ("rare", rare_cat_pipe, rare_cat_vars),
                                                 ("norm", norm_num_pipe, norm_num_vars),
                                                 ("skew", skewed_num_pipe, skewed_num_vars),
                                                 ("disc", disc_pipe, disc_num_vars)], remainder = "passthrough")


preprocessor.set_output(transform = "pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('nom',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('ohe',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['Integrated_Wireless',
                                  'Bundled_Applications']),
                                ('ord',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(add_indicator=True,
                                                                strategy='most_frequent')),
                                                 ('ord', OrdinalEncoder())...
                                 ['Battery_Life', 'Processor_Speeds']),
                                ('skew',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(strategy='median')),
                                                 ('out',
                                                  Winsorizer(capping_method='quantiles',
                                                             fold=0.06,
                                                             tail='both'))]),
                                 ['Configuration', 'Screen_Size', 'RAM',
                                  'HD_Size']),
                                ('disc',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(add_indicator=True,
                                                                strategy='median')),
                                                 ('disc',
                                                  KBinsDiscretizer(encode='ordinal',
                                                                   strategy='equal_width'))]),
                                 [])])

In [174]:
preprocessor.fit(df) # Fit the preprocessor on the dataframe df

ColumnTransformer(remainder='passthrough',
                  transformers=[('nom',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('ohe',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['Integrated_Wireless',
                                  'Bundled_Applications']),
                                ('ord',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(add_indicator=True,
                                                                strategy='most_frequent')),
                                                 ('ord', OrdinalEncoder())...
                                 ['Battery_Life', 'Processor_Speeds']),
                                ('skew',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(strategy='median')),
                                                 ('out',
                                                  Winsorizer(capping_method='quantiles',
                                                             fold=0.06,
                                                             tail='both'))]),
                                 ['Configuration', 'Screen_Size', 'RAM',
                                  'HD_Size']),
                                ('disc',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(add_indicator=True,
                                                                strategy='median')),
                                                 ('disc',
                                                  KBinsDiscretizer(encode='ordinal',
                                                                   strategy='equal_width'))]),
                                 [])])

In [175]:
df2 = preprocessor.transform(df)
df2.columns

Index(['nom__Integrated_Wireless_No', 'nom__Integrated_Wireless_Yes',
       'nom__Bundled_Applications_No', 'nom__Bundled_Applications_Yes',
       'norm__Battery_Life', 'norm__Processor_Speeds', 'skew__Configuration',
       'skew__Screen_Size', 'skew__RAM', 'skew__HD_Size',
       'remainder__Transaction_ID', 'remainder__Retail_Price'],
      dtype='object')

In [176]:
AV.AutoViz("", depVar= "remainder__Retail_Price",dfte = df2)

Shape of your Data Set loaded: (5658, 12)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  5
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  5
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    11 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['remainder__Transaction_ID']

################ Regression problem #

Number of All Scatter Plots = 15
Could not draw some Distribution Plots
No categorical or numeric vars in data set. Hence no bar charts.
All Plots done
Time to run AutoViz = 4 seconds 

 ###################### AUTO VISUALIZATION Completed ########################


nom__Integrated_Wireless_No  nom__Integrated_Wireless_Yes  \
0                 0.0                           1.0               
2                 1.0                           0.0               
3                 1.0                           0.0               
4                 1.0                           0.0               
5                 1.0                           0.0               
...                           ...                           ...   
5958              1.0                           0.0               
5959              1.0                           0.0               
5960              1.0                           0.0               
5961              0.0                           1.0               
5962              0.0                           1.0               

      nom__Bundled_Applications_No  nom__Bundled_Applications_Yes  \
0                  0.0                           1.0                
2                  0.0                           1.0                
3                  0.0                           1.0                
4                  1.0                           0.0                
5                  0.0                           1.0                
...                            ...                            ...   
5958               0.0                           1.0                
5959               1.0                           0.0                
5960               0.0                           1.0                
5961               1.0                           0.0                
5962               0.0                           1.0                

      norm__Battery_Life  norm__Processor_Speeds  skew__Configuration  \
0             4.0                   1.5                   55.0          
2             6.0                   1.5                  299.0          
3             6.0                   1.5                  303.0          
4             6.0                   1.5                  394.0          
5             5.0                   2.0                  603.0          
...                  ...                     ...                  ...   
5958          4.0                   1.5                  111.0          
5959          6.0                   2.0                  752.0          
5960          6.0                   2.4                  329.0          
5961          6.0                   2.4                  370.0          
5962          4.0                   2.4                   55.0          

      skew__Screen_Size  skew__RAM  skew__HD_Size  remainder__Retail_Price  
0           15.0            2.0          80.0               460.0           
2           15.0            1.0          80.0               490.0           
3           15.0            1.0         300.0               525.0           
4           15.0            4.0          40.0               550.0           
5           17.0            1.0          80.0               364.0           
...                 ...        ...            ...                      ...  
5958        15.0            4.0         300.0               620.0           
5959        17.0            1.0         300.0               620.0           
5960        15.0            1.0          40.0               485.0           
5961        15.0            2.0          40.0               490.0           
5962        15.0            1.0          80.0               435.0           

[5658 rows x 11 columns]

# **3. Model Fitting**

### 3.1 Pipeline with Data Preprocessing + Model Fitting

In [177]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, confusion_matrix

In [178]:
modeling_pipeline = Pipeline(steps = [("pre", preprocessor),  ("clf", DecisionTreeClassifier())])

In [179]:
X = df.drop(columns = ["Retail_Price", "Transaction_ID"])

y = df.Retail_Price

In [180]:
modeling_pipeline.fit(X,y)

Pipeline(steps=[('pre',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nom',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('ohe',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['Integrated_Wireless',
                                                   'Bundled_Applications']),
                                                 ('ord',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='most_frequent')),
                                                                  (...
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('out',
                                                                   Winsorizer(capping_method='quantiles',
                                                                              fold=0.06,
                                                                              tail='both'))]),
                                                  ['Configuration',
                                                   'Screen_Size', 'RAM',
                                                   'HD_Size']),
                                                 ('disc',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='median')),
                                                                  ('disc',
                                                                   KBinsDiscretizer(encode='ordinal',
                                                                                    strategy='equal_width'))]),
                                                  [])])),
                ('clf', DecisionTreeClassifier())])

In [181]:
pred_y = modeling_pipeline.predict(X) # make predictions using the model

confusion_matrix(y, pred_y) # Get confusion matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 3, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 4]])

In [182]:
round(accuracy_score(y, pred_y), 2)

0.45

### 3.2 Pipeline with Data Preprocessing + Model Fitting using Decision Tree Classifier

In [183]:
dt_pipeline = Pipeline(steps = [("pre", preprocessor),  ("clf", DecisionTreeClassifier())])

In [184]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 42)
dt_pipeline.fit(train_X, train_y)

Pipeline(steps=[('pre',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nom',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('ohe',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['Integrated_Wireless',
                                                   'Bundled_Applications']),
                                                 ('ord',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='most_frequent')),
                                                                  (...
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('out',
                                                                   Winsorizer(capping_method='quantiles',
                                                                              fold=0.06,
                                                                              tail='both'))]),
                                                  ['Configuration',
                                                   'Screen_Size', 'RAM',
                                                   'HD_Size']),
                                                 ('disc',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='median')),
                                                                  ('disc',
                                                                   KBinsDiscretizer(encode='ordinal',
                                                                                    strategy='equal_width'))]),
                                                  [])])),
                ('clf', DecisionTreeClassifier())])

In [185]:
train_pred = dt_pipeline.predict(train_X)
test_pred = dt_pipeline.predict(test_X)

train_accuracy = round(accuracy_score(train_y, train_pred), 2)
print(confusion_matrix(train_y, train_pred))
print(f"Model Accuracy on the Train Data is {train_accuracy}")

print("*******" * 4)


test_accuracy = round(accuracy_score(test_y, test_pred), 2)
print(confusion_matrix(test_y, test_pred))
print(f"Model Accuracy on the Test Data is {test_accuracy}")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
Model Accuracy on the Train Data is 0.47
****************************
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Model Accuracy on the Test Data is 0.29


### 3.3 Pipeline with Hyperpamater Tuning using Random Forest

In [186]:
from sklearn.ensemble import RandomForestClassifier

rf_pipeline = Pipeline(steps = [("pre", preprocessor),  ("rf", RandomForestClassifier())])
rf_pipeline.fit(X = train_X, y = train_y)

Pipeline(steps=[('pre',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nom',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('ohe',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['Integrated_Wireless',
                                                   'Bundled_Applications']),
                                                 ('ord',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='most_frequent')),
                                                                  (...
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('out',
                                                                   Winsorizer(capping_method='quantiles',
                                                                              fold=0.06,
                                                                              tail='both'))]),
                                                  ['Configuration',
                                                   'Screen_Size', 'RAM',
                                                   'HD_Size']),
                                                 ('disc',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 strategy='median')),
                                                                  ('disc',
                                                                   KBinsDiscretizer(encode='ordinal',
                                                                                    strategy='equal_width'))]),
                                                  [])])),
                ('rf', RandomForestClassifier())])

In [187]:
train_pred = rf_pipeline.predict(train_X)
test_pred = rf_pipeline.predict(test_X)

train_accuracy = round(accuracy_score(train_y, train_pred), 2)
print(confusion_matrix(train_y, train_pred))
print(f"Model Accuracy on the Train Data is {train_accuracy}")

print("*******" * 4)


test_accuracy = round(accuracy_score(test_y, test_pred), 2)
print(confusion_matrix(test_y, test_pred))
print(f"Model Accuracy on the Test Data is {test_accuracy}")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
Model Accuracy on the Train Data is 0.47
****************************
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Model Accuracy on the Test Data is 0.29


## 3.4 Pipeline with Hyperpamater Tuning on Decision Tree

In [188]:
# Set up Hyperparameters

criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]
min_samples_split = [5,10,15]
min_impurity_decrease = [0.01,0.02,0.03]

In [189]:
parameters = dict(clf__criterion=criterion,
                      clf__max_depth=max_depth,
                      clf__min_samples_split = min_samples_split,
                      clf__min_impurity_decrease = min_impurity_decrease)

In [ ]:
from sklearn.model_selection import GridSearchCV # Gridsearch for search best combination

clf_GS = GridSearchCV(dt_pipeline, parameters)
clf_GS.fit(train_X, train_y)

In [ ]:
train_pred = clf_GS.predict(train_X)
test_pred = clf_GS.predict(test_X)

train_accuracy = round(accuracy_score(train_y, train_pred), 2)
print(confusion_matrix(train_y, train_pred))
print(f"Model Accuracy on the Train Data is {train_accuracy}")

print("*******" * 10)


test_accuracy = round(accuracy_score(test_y, test_pred), 2)
print(confusion_matrix(test_y, test_pred))
print(f"Model Accuracy on the Test Data is {test_accuracy}")